[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
anyhow = "1.0.89"
sqlx = { version = "0.8", features = [ 
  "runtime-tokio", 
  "postgres",
  "uuid",
  "chrono",
  "macros",
  "migrate"
]}
r2d2_postgres = "0.18.1"
